### PR TITLE
Requests were getting hanged with 'secondGuessSourceContentType' for empty images

### PR DESCRIPTION
**Pull request by paras20xx**

### CODE REVIEW

**Comment by papandreou** [comment]
Hey Priyank, long time! 🤗 

Nice find, but it's curious that the test times out on CI? That kinda indicates that it's not fixed by this patch? 🤔

**Comment by paras20xx** [comment]
@papandreou 
hi :smile:
Yes ... I was looking into that ... on my local (with `Node JS v14.17.6`), the tests were working, realized the issue from CI report.

Also, as per the CI logs, even `npm install` seems to be failing, which is weird. I'll try to investigate if some sub-dependency is causing that issue.

**Comment by papandreou** [comment]
Thanks for giving this project a long overdue health check 👨‍⚕️

**Comment by paras20xx** [comment]
@papandreou 
The issue with `npm install` was apparently some weird/intermittent issue. I tested with some reverts and re-reverts and it eventually went away.

The issue for older versions of Node appeared to be going deeper into streams (related to "impro" package). But, I was able to implement a minor workaround in the fix part.

The "Coverage" test is failing in the "upload" step. I'm not sure if it is supposed to work or not. For your reference: https://github.com/papandreou/express-processimage/runs/3662154920

Kindly merge if the changes look alright :-)

**Comment by papandreou** [comment]
Released in 10.2.1, thanks :+1:

**Comment by paras20xx** [comment]
Thank you :grin:

**Pull request merged**
