### PR TITLE
Update processImage.js

### PR DESCRIPTION
**Pull request by outlawtorn**
fix node crash

### CODE REVIEW

**Comment by outlawtorn** [comment]
> Hi Alexander! Can you share some more details about how you've seen it crash? Maybe even include a regression test? hugs

@papandreou we have set secondGuessSourceContentType to true when trying to place a large resize number
like this ignoreAspectRatio&resize=22239,200&crop=center then our node server crashed.
We are using node 14.11.0.

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: sharp: ignoreAspectRatio() operation must follow resize
    at /home/alex/.../node_modules/express-processimage/node_modules/impro/src/engines/sharp.js:251:17
    at Array.forEach (<anonymous>)
    at Object.execute (/home/alex/.../node_modules/express-processimage/node_modules/impro/src/engines/sharp.js:186:16)
    at _flush (/home/alex/.../node_modules/express-processimage/node_modules/impro/src/Pipeline.js:99:65)
    at Impro._Pipeline.flush (/home/alex/.../node_modules/express-processimage/node_modules/impro/src/Pipeline.js:201:5)
    at Impro._Pipeline._write (/home/alex/.../node_modules/express-processimage/node_modules/impro/src/Pipeline.js:272:10)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Impro._Pipeline.Writable.write (_stream_writable.js:303:10)
    at startProcessing (/home/alex/.../node_modules/express-processimage/lib/processImage.js:266:24)
    at Transform.<anonymous> (/home/alex/.../node_modules/express-processimage/lib/processImage.js:370:17)
    at Object.onceWrapper (events.js:421:26)
    at Transform.emit (events.js:314:20)
    at Transform.EventEmitter.emit (domain.js:486:12)
    at Transform.Readable.read (_stream_readable.js:517:10)
    at flow (_stream_readable.js:990:34)
    at resume_ (_stream_readable.js:971:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on Pipeline instance at:
    at Impro._Pipeline._fail (/home/alex/.../node_modules/express-processimage/node_modules/impro/src/Pipeline.js:319:12)
    at _flush (/home/alex/.../node_modules/express-processimage/node_modules/impro/src/Pipeline.js:116:16)
    at Impro._Pipeline.flush (/home/alex/.../node_modules/express-processimage/node_modules/impro/src/Pipeline.js:201:5)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by papandreou** [comment]
Thanks! Mind turning that into a test?

**Comment by outlawtorn** [comment]
> Thanks! Mind turning that into a test?

Hi @papandreou pls check the test that i added. Thank you

**Comment by papandreou** [comment]
Thanks! Released in 10.2.3.

**Pull request merged**
